name: CI Test Action
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test-resolve-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test resolve vars action
        id: test-vars
        uses: ./
        with:
          static_inputs: |
            username=testuser
            environment=development
          # jinja_inputs: |
          #   greeting='Hello, ' + 'World!'
          #   is_prod=False
          log_outputs: true

      - name: Verify outputs
        run: |
          # Check static variables
          if [ "${{ fromJSON(steps.test-vars.outputs.all).username }}" != "testuser" ]; then
            echo "ERROR: username output doesn't match expected value"
            exit 1
          fi

          if [ "${{ fromJSON(steps.test-vars.outputs.all).environment }}" != "development" ]; then
            echo "ERROR: environment output doesn't match expected value"
            exit 1
          fi

          # Check jinja variables
          # if [ "${{ fromJson(steps.test-vars.outputs.all).greeting }}" != "Hello, World!" ]; then
          #   echo "ERROR: greeting output doesn't match expected value"
          #   exit 1
          # fi

          # if [ "${{ fromJSON(steps.test-vars.outputs.all).is_prod }}" != "False" ]; then
          #   echo "ERROR: is_prod output doesn't match expected value"
          #   exit 1
          # fi

          echo "✅ All tests passed!"
          echo "Static outputs:"
          echo "  username: ${{ fromJSON(steps.test-vars.outputs.all).username }}"
          echo "  environment: ${{ fromJSON(steps.test-vars.outputs.all).environment }}"
          # echo "Jinja outputs:"
          # echo "  greeting: ${{ fromJSON(steps.test-vars.outputs.all).greeting }}"
          # echo "  is_prod: ${{ fromJSON(steps.test-vars.outputs.all).is_prod }}"
